name: Build and publish Docker image to ghcr.io

on:
  workflow_call:
    inputs:
      docker-username:
        required: true
        type: string
      runsOn:
        required: false
        type: string
        default: 'ubuntu-20.04'
      version:
        required: true
        type: string
        description: 'Full version of the image, with branch name etc.'
      versionNumber:
        required: true
        type: string
        description: 'Version in format X.Y.Z'
      dockerContext:
        required: false
        type: string
        description: 'Docker context that will be passed to the docker build. The Git Context is used by default'
        default: "{{defaultContext}}"
      gradleProjectPath:
        required: false
        type: string
        description: 'Path to the Gradle project'
        default: '.'
      gradleParameters:
        required: false
        type: string
        description: 'List of Gradle parameters in JSON format to execute before building docker image'
        default: '[]'
    secrets:
      docker-password:
        required: true


jobs:
  docker-push:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Show custom release version
        run: echo ${{ inputs.version }}
      - name: Setup Gradle
        if: inputs.gradleParameters != '[]'
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        if: inputs.gradleParameters != '[]'
        run: ./gradlew -p ${{ inputs.gradleProjectPath }} --info --warning-mode all ${{ join(inputs.gradleParameters, ' ') }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.docker-username }}
          password: ${{ secrets.docker-password }}
      - name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT
        id: meta
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.dockerContext }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ inputs.version }}
          labels: com.exactpro.th2.${{ steps.meta.outputs.REPOSITORY_NAME }}=${{ inputs.versionNumber }}
