name: Compound Java build and Docker/Sonatype publish


on:
  workflow_call:
    inputs:
      docker-username:
        required: false
        type: string
      build-target:
        required: true
        type: string
        description: 'Use values Docker or Sonatype'
      runsOn:
        required: false
        type: string
        default: 'ubuntu-20.04'
# Trivy block
      scanner-enabled:
        required: false
        type: boolean
        default: true
        description: 'Whether scanning for vulnerabilities is enabled'
      trivy-target:
        required: false
        type: string
        default: 'os,library'
        description: 'What Trivy will scan: image, library or both'
      trivy-sensitivity:
        required: false
        type: string
        default: 'CRITICAL,HIGH,MEDIUM'
        description: 'Adjusting the Trivy Scanner Sensitivity'

    outputs:
      version:
        description: "Generated version of the image"
        value: ${{ jobs.build.outputs.version }}
    secrets:
      docker-password:
        required: false

jobs:
  build-job:
    runs-on: ${{ inputs.runsOn }}
    outputs:
      version: ${{ steps.release_ver.outputs.value }}
      versionNumber: ${{ steps.ver.outputs.release_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        id: branch
        run: echo "branch_name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Get SHA of the commit
        id: sha
#        run: echo ::set-output name=sha_short::$(git rev-parse --short HEAD)
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get release_version
        id: ver
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: release_version
      - name: Build custom release version
        id: release_ver
        run: echo "value="${{ steps.ver.outputs.release_version }}-${{ steps.branch.outputs.branch_name }}-${{ github.run_id }}-${{ steps.sha.outputs.sha_short }}"" >> $GITHUB_OUTPUT
      - name: Show custom release version
        run: echo ${{ steps.release_ver.outputs.value }}

# if Docker
  docker-push:
    if: contains(inputs.build-target, 'Docker') || contains(inputs.build-target, 'docker')
    needs: [build-job]
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT
        id: meta
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ needs.build-job.outputs.version }}
          labels: com.exactpro.th2.${{ steps.meta.outputs.REPOSITORY_NAME }}=${{ needs.build-job.outputs.versionNumber }}
  trivy-docker-scan:
    if: inputs.scanner-enabled
    needs: [docker-push, build-job]
    uses: th2-net/.github/.github/workflows/trivy-scan-github.yml@th2-4135-trivy-workflow
    with:
      image-path: ghcr.io/${{ github.repository }}:${{ needs.build-job.outputs.version }}
      target: ${{ inputs.trivy-target }}
      sensitivity: ${{ inputs.trivy-sensitivity }}


# if Sonatype
  sonatype-push:
    if: contains(inputs.build-target, 'Sonatype') || contains(inputs.build-target, 'sonatype')
    needs: [build-job]
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew --info clean build publish
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  anchore-local-scan:
    if: inputs.scanner-enabled
    needs: [build-job, sonatype-push]
    runs-on: ubuntu-20.04
    steps:
      - name: Test anchore local scanner
        id: scan
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: false
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}

