name: Compound Python check, build and pypi publish

on:
  workflow_call:
    inputs:
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'
      release:
        required: false
        type: boolean
        default: false
      pythonVersion:
        required: false
        type: string
        default: '3.8'
      scanner-enabled:
        required: false
        type: boolean
        default: true
        description: 'Whether vulnerabilities and license scanning are enabled'
      strict-scanner:
        required: false
        type: boolean
        default: true
        description: 'Whether vulnerabilities and license scanning executions are strict'

    # outputs:
    #   version:
    #     description: "Generated version of the image"
    #     value: ${{ jobs.prebuild-job.outputs.version }}
    secrets:
      # pypi-user:
      #   required: true
      #   description: 'TODO'
      pypi-password:
        required: true
        description: 'TODO'

jobs:
  
  get-version:
    name: Get version
    uses: th2-net/.github/.github/workflows/python-get-version.yml@python-workflow # FIXME: change to main
    with:
      runsOn: ${{ inputs.runsOn }}

  build-custom-version:
    name: Build custom package_version
    runs-on: ${{ inputs.runsOn }}
    needs: [get-version]
    outputs:
      custom-version: ${{ steps.release-ver.outputs.custom-version }}
    steps:
      - name: Build custom package_version
        id: release-ver
        run: echo "custom-version=${{ needs.get-version.outputs.version }}.dev${{ github.run_id }}" >> $GITHUB_OUTPUT
      - name: Show package_version
        run: echo ${{ steps.release-ver.outputs.custom-version }}

  matrix-test:
    name: Matrix test Job
    uses: th2-net/.github/.github/workflows/compound-python-matrix-test.yml@python-workflow # FIXME: change to main
  
  vulnerability-scan:
    if: inputs.scanner-enabled
    uses: th2-net/.github/.github/workflows/python-scan.yml@python-workflow # FIXME: change to main

  license-check:
    if: inputs.scanner-enabled
    uses: th2-net/.github/.github/workflows/license_check.yml@python-workflow # FIXME: change to main
    needs: [build-custom-version]
    with:
      version: ${{ needs.build-custom-version.outputs.custom-version }}
      language: python

  pypi-publish:
    name: Publish to PyPi
    needs: [build-custom-version, license-check, vulnerability-scan, matrix-test]
    if: inputs.strict-scanner && success() || !inputs.strict-scanner
    uses: th2-net/.github/.github/workflows/python-pypi-publish.yml@python-workflow # FIXME: change to main
    with:
      version: ${{ needs.build-custom-version.outputs.custom-version }}
    secrets:
      pypi-password: ${{ secrets.pypi-password }}