name: Build and publush Gradle project to Sonatype

on:
  workflow_call:
    inputs:
      runsOn:
        required: false
        type: string
        default: 'ubuntu-20.04'
      closeAndRelease:
        required: true
        type: boolean
      version:
        required: true
        type: string
    secrets:
      docker-password:
        required: false
      sonatypeUsername:
        required: false
      sonatypePassword:
        required: false
      sonatypeSigningKey:
        required: false
      sonatypeSigningPassword:
        required: false

jobs:
  sonatype-push:
    runs-on: ${{ inputs.runsOn }}
    steps:
      - uses: actions/checkout@v3
      - name: Show version
        run: echo ${{ inputs.version }}
      - name: Write custom release version to file
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
          value: ${{ inputs.version }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Release Build with Gradle
        if: ${{ inputs.closeAndRelease }}
        run: ./gradlew --info clean build publish closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.sonatypeUsername }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.sonatypePassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.sonatypeSigningKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.sonatypeSigningPassword }}
      - name: Dev Build with Gradle
        if: ${{ !inputs.closeAndRelease }}
        run: ./gradlew --info clean build publish
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.sonatypeUsername }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.sonatypePassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.sonatypeSigningKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.sonatypeSigningPassword }}