name: Dev build and publish Docker distributions to Github Container Registry ghcr.io

on:
  workflow_call:
    inputs:
      docker-username:
        required: true
        type: string
      docker-password:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.release_ver.outputs.value }}
    steps:
      - uses: actions/checkout@v2
      # Prepare custom build version
      - name: Get branch name
        id: branch
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
      - name: Get SHA of the commit
        id: sha
        run: echo ::set-output name=sha_short::$(git rev-parse --short HEAD)
      - name: Get release_version
        id: ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
      - name: Build custom release version
        id: release_ver
        run: echo ::set-output name=value::"${{ steps.ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-${{ github.run_id }}-${{ steps.sha.outputs.sha_short }}"
      - name: Show custom release version
        run: echo ${{ steps.release_ver.outputs.value }}
      # Build and publish image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ inputs.docker-username }}
          password: ${{ inputs.docker-password }}
      - run: echo "::set-output name=REPOSITORY_NAME::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        id: meta
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.release_ver.outputs.value }}
          labels: com.exactpro.th2.${{ steps.meta.outputs.REPOSITORY_NAME }}=${{ steps.ver.outputs.value }}
