name: Dev build and publish Docker distributions to Github Container Registry ghcr.io
on:
  workflow_call:
    inputs:
      docker-username:
        required: false
        type: string
        default: ${{ github.repository_owner }}
    secrets:
      docker-password:
        required: true

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/dev-docker-publish.yml@th2-4253-jar-publishing
    with:
      docker-username: ${{ inputs.docker-username }}
    secrets:
      docker-password: ${{ secrets.docker-password }}
  trivy-scan-job:
    uses: th2-net/.github/.github/workflows/trivy-scan-table.yml@main
    needs: [build-job]
    with:
      image-path: ghcr.io/${{ github.repository }}:${{ needs.build-job.outputs.version }}
      vuln-type: 'library'
