name: JS anchore vulnerabilities scanning

on:
  workflow_call:


jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Scan current project
        continue-on-error: true
        uses: anchore/scan-action@v3
        with:
          path: "."
          output-format: table