name: OWASP scan GitHub

on:
  workflow_call:
    inputs:
      multiproject:
        required: false
        type: boolean
        default: false
        description: 'false for dependencyCheckAnalyze, true for dependencyCheckAggregate'
      javaVersion:
        required: false
        type: string
        default: '11'
      javaVendor:
        required: false
        type: string
        default: 'zulu'

jobs:
  owasp-scan-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.javaVendor }} ${{ inputs.javaVersion }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.javaVendor }}
          java-version: ${{ inputs.javaVersion }}
          cache: 'gradle'
      - name: Run OWASP single-project scanning
        # continue-on-error: true
        if: ${{ !inputs.multiproject }}
        run: ./gradlew dependencyCheckAnalyze
      - name: Run OWASP multi-project scanning
        # continue-on-error: true
        if: ${{ inputs.multiproject }}
        run: ./gradlew dependencyCheckAggregate
      - name: Upload OWASP scan results to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: './build/reports/dependency-check-report.sarif'