name: OWASP scan GitHub

on:
  workflow_call:

jobs:
  owasp-scan-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run OWASP scanning
        run: ./gradlew dependencyCheckAnalyze
      - name: Upload OWASP scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: './build/reports/dependency-check-report.sarif'