name: Publish Python distribution to PyPi


on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "Target 'package_version' for publication"
      python-version:
        required: false
        type: string
        default: '3.8'
        description: "Required python version"
      pypi-url:
        required: false
        type: string
        default: 'https://upload.pypi.org/legacy/'
        description: 'TODO'
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'
    secrets:
      pypi-password:
        required: true

jobs:
  publish-to-pypi:
    name: Publish to PyPi
    runs-on: ${{ inputs.runsOn }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version for current build in package_info.json
        uses: MerthinTechnologies/edit-json-action@v1
        with:
          filename: './package_info.json'
          key: 'package_version'
          value: ${{ inputs.version }}

      - name: Setup python ${{ inputs.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build package
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi-password }}
          repository_url: ${{ inputs.pypi-url }}