name: Python vulnerabilities scanning


on:
  workflow_call:

env:
  REQUIREMENTS_PATH: ./requirements.txt
  DEP_PATH: None

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
      - name: Requiremets path to production branch
        run: echo "DEP_PATH=REQUIREMENTS_PATH" >> $GITHUB_ENV
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master