name: Python vulnerabilities scanning


on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
      - run: ls
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master