name: Python vulnerabilities scanning


on:
  workflow_call:

env:
  DEP_PATH: requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master

#      - name: Security vulnerabilities scan
#        uses: aufdenpunkt/python-safety-check@master
#        with:
#          scan_requirements_file_only: 'true'

      - name: Python security check using Bandit
        uses: Joel-hanson/bandit-report-artifacts@V1

      - name: install
        run: python -m pip install .
      - uses: pypa/gh-action-pip-audit@v1.0.6
        with:
          inputs: requirements.txt
