name: Python vulnerabilities scanning


on:
  workflow_call:

env:
  DEP_PATH: requirements.txt

jobs:
  scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master
        with:
          scan_requirements_file_only: 'true'
