name: Run matrix Python test


on:
  workflow_call:
    inputs:
      test-dir:
        required: false
        type: string
        default: ''
        description: 'Directory with pytests'
      test-ignore-dir:
        required: false
        type: string
        default: ''
        description: 'Python version'
      requirements-file:
        required: false
        type: string
        default: 'requirements.txt'
        description: 'Path to requirements'
      python-version:
        required: false
        type: string
        default: '3.8'
        description: 'Python version'
      runsOn:
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  test:
    name: "Test (Python:${{ inputs.python-version }},Image:${{ inputs.runsOn }})"
    runs-on: ${{ inputs.runsOn }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup python ${{ inputs.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      if: ${{ inputs.requirements-file != '' }} 
      run: pip install -r "${{ inputs.requirements-file }}"
    
    - name: Show dependencies
      run: pip list

    - name: Run tests
      if: ${{ inputs.test-ignore-dir != '' }}
      run: | 
        args="-n auto "
        if [ -n "${{ inputs.test-dir }}" ];then
          args+="${{ inputs.test-dir }} "
        fi
        if [ -n "${{ inputs.test-ignore-dir }}" ]; then
          args+="--ignore ${{ inputs.test-ignore-dir }} "
        fi

        echo "Args: ${args}"

        pytest $args
        
