name: Python vulnerabilities scanning


on:
  workflow_call:

env:
  DEP_PATH: ../../requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master
      - run: ls
      - run: ls ../
      - run: ls ../../
      - run: ls ../../../
      - run: ls ../../../../
      - name: Security vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master