name: Trivy scan Docker image for vulnerable dependencies and publish results to secutity tab

on:
  workflow_call:
    inputs:
      image-path:
        required: true
        type: string
      target:
        required: false
        type: string
        default: 'os,library'
        description: 'What Trivy will scan: image, library or both'
      sensitivity:
        required: false
        type: string
        default: 'CRITICAL,HIGH,MEDIUM'
        description: 'Adjusting the Scanner Sensitivity'
      exitCode:
        required: false
        type: string
        default: '0'
        description: 'Exit code when specified vulnerabilities are found (1 for fail, 0 for ignore)'
      ignoreUnfixed:
        required: false
        type: boolean
        default: false
        description: 'Ignore vulnerabilities that are impossible to fix at the moment'
      offlineScan:
        required: false
        type: boolean
        default: false
        description: 'Force trivy to scan an image without db update'

jobs:
  trivy-scan-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Show scanning target
        run: echo ${{ inputs.image-path }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-path }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ inputs.sensitivity }}
          exit-code: ${{ inputs.exitCode }}
          ignore-unfixed: ${{ inputs.ignoreUnfixed }}
          vuln-type: ${{ inputs.target }}
        env:
          TRIVY_OFFLINE_SCAN: ${{ inputs.offlineScan }}
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'