name: Trivy scan for vulnerable dependencies and publish results to secutity tab

on:
  workflow_call:
    inputs:
      image-path:
        required: true
        type: string
      target:
        required: false
        type: string
        default: 'os,library'
        description: 'What Trivy will scan: image, library or both'
      sensitivity:
        required: false
        type: string
        default: 'CRITICAL,HIGH,MEDIUM'
        description: 'Adjusting the Scanner Sensitivity'

jobs:
  trivy-scan-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Show scanning target
        run: echo ${{ inputs.image-path }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-path }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: ${{ inputs.sensitivity }}
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: ${{ inputs.target }}
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'